package steamid

import "testing"

func TestSteamIDFromTicket(t *testing.T) {
	type args struct {
		ticket string
	}
	tests := []struct {
		name    string
		args    args
		want    uint64
		wantErr bool
	}{
		{
			name: "1",
			args: args{
				ticket: `FAAAALa64Wt6YABjulYAAAEAEAFuE8pnGAAAAAEAAAACAAAAmcpFl5dLjhV3NdcwGwEAAOIAAABiAAAABAAAAHRH1AEBABAB1GMEAJwQmSVlCqjAAAAAALD9v2cwrdtnAQDVIgEACACQAAYAAAAMNAYAAAAgNAYAAAA0NAYAAAA+NAYAAABINAYAAABSNAYAAABcNAYAAAAAAF94BcbVfVrkfbWIOWU+s/nPmrOt+eHItmb/eDkIZ9mJIazVUF3Tfb1xwbz7v2d5Mt3DK0MBqC+Wk8lapoDSQbhjQTqmz6gvCSonLUT7DAXYjBxtdfbh+lN3w03s8sIIBv5/TB0Ww7gkwDGMnS6PEs12KCsOoF0L6wc1QkGjd98WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`,
			},
			want:    76561197960287930,
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := FromTicket(tt.args.ticket)
			if (err != nil) != tt.wantErr {
				t.Errorf("SteamIDFromTicket() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.want {
				t.Errorf("SteamIDFromTicket() got = %v, want %v", got, tt.want)
			}
		})
	}
}
