// Code generated by "stringer -type=EAreaCode"; DO NOT EDIT.

package areacode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CentralIndianRidge-0]
	_ = x[MidAtlanticRidge-10]
	_ = x[EastOfTheHawaiianIslands-20]
	_ = x[SouthAtlanticOcean-30]
	_ = x[IndianOcean-40]
	_ = x[NorthPacificOcean-70]
	_ = x[SouthPacificOcean-80]
	_ = x[NorthAtlanticOcean-90]
}

const (
	_EAreaCode_name_0 = "CentralIndianRidge"
	_EAreaCode_name_1 = "MidAtlanticRidge"
	_EAreaCode_name_2 = "EastOfTheHawaiianIslands"
	_EAreaCode_name_3 = "SouthAtlanticOcean"
	_EAreaCode_name_4 = "IndianOcean"
	_EAreaCode_name_5 = "NorthPacificOcean"
	_EAreaCode_name_6 = "SouthPacificOcean"
	_EAreaCode_name_7 = "NorthAtlanticOcean"
)

func (i EAreaCode) String() string {
	switch {
	case i == 0:
		return _EAreaCode_name_0
	case i == 10:
		return _EAreaCode_name_1
	case i == 20:
		return _EAreaCode_name_2
	case i == 30:
		return _EAreaCode_name_3
	case i == 40:
		return _EAreaCode_name_4
	case i == 70:
		return _EAreaCode_name_5
	case i == 80:
		return _EAreaCode_name_6
	case i == 90:
		return _EAreaCode_name_7
	default:
		return "EAreaCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
