// Code generated by "stringer -type=EWeaponRange"; DO NOT EDIT.

package weaponrange

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Close-0]
	_ = x[Mid-1]
	_ = x[Long-2]
	_ = x[End-3]
}

const _EWeaponRange_name = "CloseMidLongEnd"

var _EWeaponRange_index = [...]uint8{0, 5, 8, 12, 15}

func (i EWeaponRange) String() string {
	if i >= EWeaponRange(len(_EWeaponRange_index)-1) {
		return "EWeaponRange(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EWeaponRange_name[_EWeaponRange_index[i]:_EWeaponRange_index[i+1]]
}
