// Code generated by "stringer -type=ERewardType"; DO NOT EDIT.

package fobeventreward

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidRewardType-0]
	_ = x[NormalDefense-1]
	_ = x[NormalSneak-2]
	_ = x[OneEventTaskSneak-3]
}

const _ERewardType_name = "InvalidRewardTypeNormalDefenseNormalSneakOneEventTaskSneak"

var _ERewardType_index = [...]uint8{0, 17, 30, 41, 58}

func (i ERewardType) String() string {
	if i >= ERewardType(len(_ERewardType_index)-1) {
		return "ERewardType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ERewardType_name[_ERewardType_index[i]:_ERewardType_index[i+1]]
}
