package fobeventreward 

var FOBRewards = []Reward{
	{
		ID:         0,
		EventID:    -1,
		Type:       NormalDefense,
		Reward:     2000,
		TaskTypeID: 79, 
		Threshold:  1,
	},
	{
		ID:         1,
		EventID:    -1,
		Type:       NormalDefense,
		Reward:     4000,
		TaskTypeID: 78, 
		Threshold:  1,
	},
	{
		ID:         2,
		EventID:    -1,
		Type:       NormalDefense,
		Reward:     500,
		TaskTypeID: 96, 
		Threshold:  1,
	},
	{
		ID:         3,
		EventID:    -1,
		Type:       NormalDefense,
		Reward:     500,
		TaskTypeID: 97, 
		Threshold:  5,
	},
	{
		ID:         4,
		EventID:    -1,
		Type:       NormalSneak,
		Reward:     2000,
		TaskTypeID: 10, 
		Threshold:  10,
	},
	{
		ID:         5,
		EventID:    -1,
		Type:       NormalSneak,
		Reward:     1000,
		TaskTypeID: 8, 
		Threshold:  5,
	},
	{
		ID:         6,
		EventID:    -1,
		Type:       NormalSneak,
		Reward:     2000,
		TaskTypeID: 69, 
		Threshold:  1,
	},
	{
		ID:         7,
		EventID:    -1,
		Type:       NormalSneak,
		Reward:     4000,
		TaskTypeID: 41, 
		Threshold:  1,
	},
	{
		ID:         8,
		EventID:    4,
		Type:       OneEventTaskSneak,
		Reward:     300,
		TaskTypeID: 3, 
		Threshold:  1,
	},
	{
		ID:         9,
		EventID:    4,
		Type:       OneEventTaskSneak,
		Reward:     350,
		TaskTypeID: 37, 
		Threshold:  60,
	},
	{
		ID:         10,
		EventID:    4,
		Type:       OneEventTaskSneak,
		Reward:     600,
		TaskTypeID: 2, 
		Threshold:  1,
	},
	{
		ID:         11,
		EventID:    4,
		Type:       OneEventTaskSneak,
		Reward:     1160,
		TaskTypeID: 8, 
		Threshold:  8,
	},
	{
		ID:         12,
		EventID:    4,
		Type:       OneEventTaskSneak,
		Reward:     2020,
		TaskTypeID: 9, 
		Threshold:  1,
	},
	{
		ID:         13,
		EventID:    4,
		Type:       OneEventTaskSneak,
		Reward:     1100,
		TaskTypeID: 67, 
		Threshold:  1,
	},
	{
		ID:         14,
		EventID:    4,
		Type:       OneEventTaskSneak,
		Reward:     1400,
		TaskTypeID: 69, 
		Threshold:  1,
	},
	{
		ID:         15,
		EventID:    4,
		Type:       OneEventTaskSneak,
		Reward:     2100,
		TaskTypeID: 74, 
		Threshold:  1,
	},
	{
		ID:         16,
		EventID:    24,
		Type:       OneEventTaskSneak,
		Reward:     660,
		TaskTypeID: 3, 
		Threshold:  2,
	},
	{
		ID:         17,
		EventID:    24,
		Type:       OneEventTaskSneak,
		Reward:     580,
		TaskTypeID: 37, 
		Threshold:  90,
	},
	{
		ID:         18,
		EventID:    24,
		Type:       OneEventTaskSneak,
		Reward:     1320,
		TaskTypeID: 2, 
		Threshold:  2,
	},
	{
		ID:         19,
		EventID:    24,
		Type:       OneEventTaskSneak,
		Reward:     2610,
		TaskTypeID: 8, 
		Threshold:  15,
	},
	{
		ID:         20,
		EventID:    24,
		Type:       OneEventTaskSneak,
		Reward:     3030,
		TaskTypeID: 9, 
		Threshold:  1,
	},
	{
		ID:         21,
		EventID:    24,
		Type:       OneEventTaskSneak,
		Reward:     1650,
		TaskTypeID: 67, 
		Threshold:  1,
	},
	{
		ID:         22,
		EventID:    24,
		Type:       OneEventTaskSneak,
		Reward:     2100,
		TaskTypeID: 69, 
		Threshold:  1,
	},
	{
		ID:         23,
		EventID:    24,
		Type:       OneEventTaskSneak,
		Reward:     3150,
		TaskTypeID: 74, 
		Threshold:  1,
	},
}
