// Code generated by "stringer -type Platform"; DO NOT EDIT.

package platform

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Steam-1]
	_ = x[PS3-2]
	_ = x[PS4-3]
	_ = x[XBOX360-4]
	_ = x[XBOXOne-5]
}

const _Platform_name = "InvalidSteamPS3PS4XBOX360XBOXOne"

var _Platform_index = [...]uint8{0, 7, 12, 15, 18, 25, 32}

func (i Platform) String() string {
	if i < 0 || i >= Platform(len(_Platform_index)-1) {
		return "Platform(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Platform_name[_Platform_index[i]:_Platform_index[i+1]]
}
