// Code generated by "stringer -type=EPlacedType"; DO NOT EDIT.

package fobplaced

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlacedTypeInvalid-0]
	_ = x[MINE-1]
	_ = x[CAMERA-2]
}

const _EPlacedType_name = "PlacedTypeInvalidMINECAMERA"

var _EPlacedType_index = [...]uint8{0, 17, 21, 27}

func (i EPlacedType) String() string {
	if i >= EPlacedType(len(_EPlacedType_index)-1) {
		return "EPlacedType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EPlacedType_name[_EPlacedType_index[i]:_EPlacedType_index[i+1]]
}
