// Code generated by "stringer -type=EFOBTargetType"; DO NOT EDIT.

package fobtargettype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[PICKUP-1]
	_ = x[PICKUP_HIGH-2]
	_ = x[ENEMY-3]
	_ = x[FR_ENEMY-4]
	_ = x[NUCLEAR-5]
	_ = x[TRIAL-6]
	_ = x[EVENTS-7]
	_ = x[INJURY-8]
	_ = x[CHALLENGE-9]
	_ = x[DEPLOYED-10]
	_ = x[EMERGENCY-11]
}

const _EFOBTargetType_name = "InvalidPICKUPPICKUP_HIGHENEMYFR_ENEMYNUCLEARTRIALEVENTSINJURYCHALLENGEDEPLOYEDEMERGENCY"

var _EFOBTargetType_index = [...]uint8{0, 7, 13, 24, 29, 37, 44, 49, 55, 61, 70, 78, 87}

func (i EFOBTargetType) String() string {
	if i >= EFOBTargetType(len(_EFOBTargetType_index)-1) {
		return "EFOBTargetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EFOBTargetType_name[_EFOBTargetType_index[i]:_EFOBTargetType_index[i+1]]
}
