// Code generated by "stringer -type=ESection"; DO NOT EDIT.

package sectionstat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Base-0]
	_ = x[Combat-1]
	_ = x[Develop-2]
	_ = x[Medical-3]
	_ = x[Security-4]
	_ = x[Spy-5]
	_ = x[Support-6]
}

const _ESection_name = "BaseCombatDevelopMedicalSecuritySpySupport"

var _ESection_index = [...]uint8{0, 4, 10, 17, 24, 32, 35, 42}

func (i ESection) String() string {
	if i >= ESection(len(_ESection_index)-1) {
		return "ESection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ESection_name[_ESection_index[i]:_ESection_index[i+1]]
}
