// Code generated by "stringer -type=EGuardRank"; DO NOT EDIT.

package guardrank

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[E-0]
	_ = x[D-1]
	_ = x[C-2]
	_ = x[B-3]
	_ = x[A-4]
	_ = x[APlus-5]
	_ = x[APlusPlus-6]
	_ = x[S-7]
	_ = x[SPlus-8]
	_ = x[SPlusPlus-9]
}

const _EGuardRank_name = "EDCBAAPlusAPlusPlusSSPlusSPlusPlus"

var _EGuardRank_index = [...]uint8{0, 1, 2, 3, 4, 5, 10, 19, 20, 25, 34}

func (i EGuardRank) String() string {
	if i >= EGuardRank(len(_EGuardRank_index)-1) {
		return "EGuardRank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EGuardRank_name[_EGuardRank_index[i]:_EGuardRank_index[i+1]]
}
