// Code generated by "stringer -type=ETimeBonusType"; DO NOT EDIT.

package fobeventtimebonus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidTimeBonusType-0]
	_ = x[NormalDefense-1]
	_ = x[NormalSneak-2]
	_ = x[OneEventTaskSneak-3]
}

const _ETimeBonusType_name = "InvalidTimeBonusTypeNormalDefenseNormalSneakOneEventTaskSneak"

var _ETimeBonusType_index = [...]uint8{0, 20, 33, 44, 61}

func (i ETimeBonusType) String() string {
	if i >= ETimeBonusType(len(_ETimeBonusType_index)-1) {
		return "ETimeBonusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ETimeBonusType_name[_ETimeBonusType_index[i]:_ETimeBonusType_index[i+1]]
}
