// Code generated by "stringer -type=EFobColor"; DO NOT EDIT.

package fobcolor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Plain1TerracottaOrange-0]
	_ = x[Plain2SlateBlue-1]
	_ = x[Plain3DarkSlateGray-2]
	_ = x[Plain4ChestnutBrown-3]
	_ = x[Plain5LightSlateGray-4]
	_ = x[Plain6OliveDrab-5]
	_ = x[Plain7DustyRose-6]
	_ = x[Plain8Mocha-7]
	_ = x[Camo1Square-8]
	_ = x[Camo2Desert-9]
	_ = x[Camo3TigerStripe-10]
	_ = x[Camo4Veil-11]
	_ = x[Camo5Woodland-12]
	_ = x[Camo6MuddyBrown-13]
	_ = x[Camo7Christmas-14]
	_ = x[Camo8Forest-15]
	_ = x[Camo9Zebra-16]
	_ = x[Camo10Wooden-17]
	_ = x[Camo11Rust-18]
	_ = x[Camo12YellowWashedOut-19]
	_ = x[End-20]
}

const _EFobColor_name = "Plain1TerracottaOrangePlain2SlateBluePlain3DarkSlateGrayPlain4ChestnutBrownPlain5LightSlateGrayPlain6OliveDrabPlain7DustyRosePlain8MochaCamo1SquareCamo2DesertCamo3TigerStripeCamo4VeilCamo5WoodlandCamo6MuddyBrownCamo7ChristmasCamo8ForestCamo9ZebraCamo10WoodenCamo11RustCamo12YellowWashedOutEnd"

var _EFobColor_index = [...]uint16{0, 22, 37, 56, 75, 95, 110, 125, 136, 147, 158, 174, 183, 196, 211, 225, 236, 246, 258, 268, 289, 292}

func (i EFobColor) String() string {
	if i >= EFobColor(len(_EFobColor_index)-1) {
		return "EFobColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EFobColor_name[_EFobColor_index[i]:_EFobColor_index[i+1]]
}
